import { Category } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'formula1',
    name: 'Formula 1',
    color: '#e10600',
    icon: '🏎️',
    description: 'Formula 1 Grand Prix races',
    isDefault: true,
  },
  {
    id: 'motogp',
    name: 'MotoGP',
    color: '#ff6600',
    icon: '🏍️',
    description: 'MotoGP motorcycle racing events',
    isDefault: true,
  },
  {
    id: 'nascar',
    name: 'NASCAR',
    color: '#ffd700',
    icon: '🏁',
    description: 'NASCAR Cup Series races',
    isDefault: true,
  },
  {
    id: 'wec',
    name: 'WEC',
    color: '#0066cc',
    icon: '🏆',
    description: 'World Endurance Championship',
    isDefault: true,
  },
  {
    id: 'rally',
    name: 'Rally',
    color: '#00a650',
    icon: '🚗',
    description: 'WRC and rally championships',
    isDefault: true,
  },
  {
    id: 'indycar',
    name: 'IndyCar',
    color: '#001489',
    icon: '🏎️',
    description: 'IndyCar Series races',
    isDefault: true,
  },
  {
    id: 'formulae',
    name: 'Formula E',
    color: '#00aaff',
    icon: '⚡',
    description: 'Formula E electric racing',
    isDefault: true,
  },
  {
    id: 'other',
    name: 'Other',
    color: '#6b7280',
    icon: '🏁',
    description: 'Other motorsports events',
    isDefault: true,
  },
];
